services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/emmanig/cp32/tree/main/proyecto%20sp32
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://emma12:emma12@cluster0.nakgr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
